[package]
name = "micrograd"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
graphviz-rust = "0.9.3"
ordered-float = "4.6.0"
thiserror = "2.0.11"

[dev-dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.1"
